-- learn more on https://docs.dataform.co/guides/operations/
-- learn more on https://cloud.google.com/dataform/docs/custom-sql

config {
  hasOutput: true,
  type: "operations",
  schema: dataform.projectConfig.vars.RAW_DATA,
  tags: ["LOAD_DATA"],
  name: "vehicles"
}

LOAD DATA OVERWRITE sandbox-johnny-boniface.dataform_training.vehicles
FROM FILES (
  format = "JSON",
  uris = ["gs://training-workspace/vehicles/starwars_vehicles.json"]
);
